# Python Basics

Max Calzada

Thank you [Prof. Isken](http://www.sba.oakland.edu/faculty/index_SBA.asp?ID=46) for sharing your [video lessons](http://www.sba.oakland.edu/faculty/isken/courses/mis5470_w22/python_intro_1.html) online. I have used the material on your website to teach myself Python.

## Variable Naming

In [4]:
#name a variable
Mark = 85

#naming a variable returns the value
Mark

85

In [6]:
#printing text
print('The variable Mark =', Mark)

The variable Mark = 85


## Dataset Basics

In [7]:
#listing the files in the data folder
!ls data/*.csv

data/SchedDaysAdv.csv    data/inflammation-06.csv data/inflammation-12.csv
data/inflammation-01.csv data/inflammation-07.csv data/small-01.csv
data/inflammation-02.csv data/inflammation-08.csv data/small-02.csv
data/inflammation-03.csv data/inflammation-09.csv data/small-03.csv
data/inflammation-04.csv data/inflammation-10.csv
data/inflammation-05.csv data/inflammation-11.csv


In [11]:
#numpy
import numpy

numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [15]:
#name the dataset
inflm = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

inflm

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [16]:
#data dimensions
inflm.shape

(60, 40)

In [18]:
#Display
#first 5 rows
#first 7 colums

inflm[:5, 0:7]

#Python index begins at 0.

array([[0., 0., 1., 3., 1., 2., 4.],
       [0., 1., 2., 1., 2., 1., 3.],
       [0., 1., 1., 3., 3., 2., 6.],
       [0., 0., 2., 0., 4., 2., 2.],
       [0., 1., 1., 3., 3., 1., 3.]])

In [22]:
#slice section of data

# I want to display the 18th to 24th rows inclusive
# and the 16th to 23rd columns inclusive

section = inflm[17:24, 15:23]
section

array([[ 4., 14.,  7.,  8., 14., 13., 19.,  6.],
       [11., 15., 17., 11., 12.,  7., 12.,  7.],
       [13.,  6.,  5.,  9., 16.,  9., 19., 16.],
       [15., 13.,  6.,  5.,  5., 18., 19.,  9.],
       [ 5., 12., 12.,  8.,  5., 12., 10., 16.],
       [14.,  5.,  5., 17., 13., 16., 15., 13.],
       [13.,  7., 14., 11., 15., 14., 13.,  5.]])

## Summary Statistics

In [34]:
inflm.mean()

6.14875

In [33]:
inflm.std()

4.613833197118566

In [35]:
inflm.max()

20.0

In [36]:
inflm.min()

0.0